---

spring:
  cloud:
    config:
      server:
        git:
          uri: ${vcap.services.git-config-store.url}
          # ONLY include username and pwd if the repo is private
          # username:
          # password:
security:
  user:
    name: {username}
    password: {password}